### ISSUE TITLE
To Do

### ISSUE THREAD

**Issue by sjy5386** [sjy5386/typing-game#1]
### 11주차(11월 11일~)

- [x] 조구성(2인 1조)
- [x] 프로젝트 이해
- [x] 기능 결정 및 메뉴 설계
- [x] 작업 분담
- [x] 9장 학습, 14장 메뉴 학습 후 프레임 윈도우의 Layout 결정 9장 open challenge 참고
- [x] 메뉴 달기

### 12주차(11월 18일~)

- [x] 10장, 11장 학습(이벤트)
- [x] 단어 파일 읽기 후 랜덤하게 한 단어를 선택하여 JLabel로 화면에 출력
- [x] 키 이벤트로 단어 맞추기
- [x] 맞추고 나면 다른 단어 교체
- [x] 단어 입력 화면 만들어 파일에 단어 저장
- [x] 사용자 UI 개선

### 13주차(11월 25일 ~)

- [x] 13장 학습(스레드) 후 스레드로 단어 움직이기, 13장 실습문제 참고

### 14주차(12월 2일 ~)

- [x] 12장 학습 후 : 배경 이미지 달기 및 교체
- [x] 미니 완료

### 15주차(12월 9일 ~)

- [x] 기말 시험

### 16주차(12월 16일 ~)

- [x] 보강 주
- [x] 최종 데모 및 평가

**Comment by sjy5386** [comment]
[words.txt](https://github.com/sjy5386/typing-game/files/3882422/words.txt)

**Comment by sjy5386** [comment]
![cap1](https://user-images.githubusercontent.com/13289043/69540811-f9fae000-0fca-11ea-99cc-2445473692f0.png)

**Comment by sjy5386** [comment]
![캡처](https://user-images.githubusercontent.com/13289043/69540835-0848fc00-0fcb-11ea-9489-64b53ab376a9.PNG)
![단어장](https://user-images.githubusercontent.com/13289043/69540839-0c751980-0fcb-11ea-8a5d-96a00dc545c6.PNG)
![단어장 확인](https://user-images.githubusercontent.com/13289043/69540842-0f700a00-0fcb-11ea-841a-7688093bc6ec.PNG)
![단어맞춤](https://user-images.githubusercontent.com/13289043/69540846-10a13700-0fcb-11ea-9a51-c85064f4c729.PNG)

**Comment by sjy5386** [comment]
[http://soundbible.com/suggest.php?q=gun](http://soundbible.com/suggest.php?q=gun)

**Comment by sjy5386** [comment]
[Barreta M9](http://soundbible.com/1906-Barreta-M9.html)

**Comment by sjy5386** [comment]
![cap3](https://user-images.githubusercontent.com/13289043/69958920-312c3c80-1549-11ea-9e9d-a937cfd074b1.PNG)

**Comment by Disarmy** [comment]
[kor_words.txt](https://github.com/sjy5386/typing-game/files/3967183/kor_words.txt)
